export default function() {
	return [
		{spelling:'bon vivant', 
		 definition: 'a person having cultivated, refined, and sociable tastes especially with respect to food and drink and company',
		 example: '',
		 etymology: 'French: literally "good liver," as in one who lives (First Known Use: circa 1695)'},
		{spelling:'denouement',
	   definition: '',
	   example: '',
	   etymology: ''},
		{spelling:'ineffable',
	   definition: '',
	   example: '',
	   etymology: ''},
		{spelling:'savoir fare',
	   definition: '',
	   example: '',
	   etymology: ''},
		{spelling:'equanimity',
	   definition: '',
	   example: '',
	   etymology: ''},
		{spelling:'inimitable',
	   definition: '',
	   example: '',
	   etymology: ''},
		{spelling:'polymath',
	   definition: '',
	   example: '',
	   etymology: ''},
		{spelling:'voluble',
	   definition: '',
	   example: '',
	   etymology: ''}
	]
}