export default function() {
	return [
		{spelling:'bon vivant', 
		 definition: 'a person having cultivated, refined, and sociable tastes especially with respect to food and drink and company',
		 example: '',
		 etymology: 'French: literally "good liver," as in one who lives (First Known Use: circa 1695)'},
		{spelling:'denouement',
	   definition: '(1) the outcome of a complex, perhaps doubtful, series of events (2) the final outcome of the main dramatic complication in a literay work',
	   example: '',
	   etymology: 'French: literally "untying", from Old French: desoner, to tie (First Known Use: 1705)'},
		{spelling:'ineffable',
	   definition: '(1) incapable of being described in words (2) not to be uttered',
	   example: '',
	   etymology: 'Middle English: from Latin ineffabilis, from in + effabilis capable of being expressed (First Known Use: 14th century'},
		{spelling:'savoir faire',
	   definition: 'capacity for appropriate action, especially: a polished sureness in social behavior',
	   example: '',
	   etymology: 'French: literally "knowing how to do" (First Known Use: 1815)'},
		{spelling:'equanimity',
	   definition: '(1) evenness of mind especially under stress (2) right disposition',
	   example: '',
	   etymology: 'Latin: aequanimitas, from aequo animo with even mind (First Known Use: circa 1616)'},
		{spelling:'inimitable',
	   definition: '(1) so good or unusual as to be impossible to copy (2) unique',
	   example: '',
	   etymology: 'Middle English: from Latin inimitabilis, from in+ imitabilis imitable (First Known Use: 15th century)'},
		{spelling:'polymath',
	   definition: 'a person whose expertise spans a significant number of different subject areas',
	   example: '',
	   etymology: 'Greek: polymathes very learned, from poly + manthanein to learn (First Known Use: 1621)'},
		{spelling:'voluble',
	   definition: '(1) speaking or spoken incessantly and fluently (2) an individual who speaks easily and often (3) eaily rolling or turning',
	   example: '',
	   etymology: 'Middle English: from Latin volubilis, from volvere to roll (First Known Use: 15th century'}
	]
}